services:

  web:
    build: apache
    hostname: web
    ports:
      - 8000:80
      - 443:443
    networks:
      rede_test:
        aliases:
          - a23danielgs.ddnsfree.com
          - www.a23danielgs.ddnsfree.com
    volumes:
      - ./app:/app
      - ./apache/drupal.conf:/etc/apache2/sites-enabled/drupal.conf
      - ./certs:/certs

  basededatos:
    image: mariadb
    volumes:
      - datos:/var/lib/mysql
    env_file:
      - mariadb.env
    secrets:
      - mariadb
    networks:
      - rede_test

  phpmyadmin:
    image: phpmyadmin
    networks:
      - rede_test
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=basededatos

secrets:
  mariadb:
    file: .mariadb.txt

networks:
  rede_test:
volumes:
  datos: