services:

  web:
    build: apache
    hostname: web
    ports:
      - 8000:80
      - 443:443
    networks:
      rede_test:
        aliases:
          - a23danielgs.ddnsfree.com
          - www.a23danielgs.ddnsfree.com
    volumes:
      - ./app/:/app
      - ./configs/:/etc/apache2/sites-enabled/
      - ./certs:/certs

networks:
  rede_test:
volumes:
  datos: